name: Go CI with Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated to latest version

      - name: Update packages list
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install -y libgpgme-dev

      - name: Set up Go 1.20.5
        uses: actions/setup-go@v4 # Updated to latest version
        with:
          go-version: 1.20.5

      - name: Build
        run: |
          go build -o longteac_${{github.ref_name}}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.LONGTEAC_GH }}
          tag: ${{ github.ref_name }}
        with:
          tag_name: ${{ env.tag }}
          files: |
            longteac_${{github.ref_name}}
